### ISSUE TITLE
Add Food Diary Settings to Settings Page

### ISSUE THREAD

**Issue by kpwags** [kpwags/fitness-tracker#29]
Food Diary Settings Should Include:
- Groupings (Breakfast, Lunch, Dinner, etc.)
- Custom Foods
- Recipes

---

## Tasks
- [x] Food Groupings
- [x] Custom Foods
- [x] Recipes

## Unit Tests
- [x] Food Groupings
- [x] Custom Foods
- [x] Recipes

**Comment by kpwags** [comment]
### API Unit Tests

- [ ] Food Service - Food Search
- [ ] Food Controller - Food Search
- [ ] Recipe Service - Get By ID
- [ ] Recipe Service - Get for User
- [ ] Recipe Service - Add
- [ ] Recipe Service - Update
- [ ] Recipe Service - Delete
- [ ] Recipe Controller - Get By ID
- [ ] Recipe Controller - Get for User
- [ ] Recipe Controller - Add
- [ ] Recipe Controller - Update
- [ ] Recipe Controller - Delete

**Comment by kpwags** [comment]
Also need to figure out #46
